spring.application.name=communaute

# PGHOST=postgres.railway.internal
# PGPORT=5432

spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=njvHbYVpsIIjOIykojAQFtNhVnlSgfEF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.enable-default-api-docs=true
springdoc.swagger-ui.path=/api/docs

server.error.include-stacktrace=never