spring.application.name=communaute

spring.datasource.url=jdbc:postgresql://localhost:5432/communaute
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.enable-default-api-docs=true
springdoc.swagger-ui.path=/api/docs

server.error.include-stacktrace=never